import Header from "@/components/my_components/Header";
import "./globals.css";
import { GoogleOAuthProvider } from "@react-oauth/google";
import ConvexClientProvider from "./ConvexClientProvider";


import Provider from "./Provider";


export const metadata = {
  title: "BluePrint",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        
          <ConvexClientProvider>
            <GoogleOAuthProvider
              clientId={process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID}
            >
              <Header />
            <Provider>
              {children}
            </Provider>
              
            </GoogleOAuthProvider>
          </ConvexClientProvider>
       
      </body>
    </html>
  );
}
